version: '3.8'

services:
  # Frontend - React + Nginx (SIN PUERTOS EXPUESTOS)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # NO EXPONEMOS PUERTOS - el túnel maneja todo
    restart: unless-stopped
    networks:
      - tunnel-network
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://api.reportediario.inemec.com/api/v1

  # Backend - FastAPI + Python (SIN PUERTOS EXPUESTOS)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # NO EXPONEMOS PUERTOS - el túnel maneja todo
    restart: unless-stopped
    networks:
      - tunnel-network
    environment:
      - PYTHONPATH=/app
      - PORT=8001
      # CORS para subdominios del túnel
      - CORS_ORIGINS=["https://reportediario.inemec.com","https://api.reportediario.inemec.com","http://localhost:3000","http://localhost:5173"]
    volumes:
      # Persistir datos de Excel
      - ./data:/app/data
      - ./logs:/app/logs

  # Cloudflare Tunnel - LA MAGIA SUCEDE AQUÍ
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    networks:
      - tunnel-network
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    depends_on:
      - frontend
      - backend

networks:
  tunnel-network:
    driver: bridge

volumes:
  admin_data:
    driver: local